version: "3.8"

services:
  worker:
    build:
      context: "./DemoApp"
      dockerfile: "./Worker.Dockerfile"
    environment:
      DOTNET_ENVIRONMENT: "Development"

  publisher:
    build:
      context: "./DemoApp"
      dockerfile: "./Publisher.Dockerfile"
    environment:
      DOTNET_ENVIRONMENT: "Development"
