version: "3.8"

services:
  worker:
    build:
      context: "./DemoApp"
      dockerfile: "./Worker.Dockerfile"
    environment:
      DOTNET_ENVIRONMENT: "Development"
      ConnectionStrings__Redis: "redis"

  publisher:
    build:
      context: "./DemoApp"
      dockerfile: "./Publisher.Dockerfile"
    environment:
      DOTNET_ENVIRONMENT: "Development"
      ConnectionStrings__Redis: "redis"

  redis:
    image: "redis:7-alpine"
    command:
      - "--save"
      - "60"
      - "1"
    volumes:
      - "redis-data:/data"

volumes:
  redis-data: