apiVersion: v1
kind: Service
metadata:
  name: {{ include "app.fullname" . }}-elastic
  labels:
    {{- include "elastic.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "elastic.selectorLabels" . | nindent 4 }}
  ports:
    - port: 9200
  clusterIP: None
