name: DemoApp main workflow

on:
  push:
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2.5.0

      - name: Setup dotnet
        uses: actions/setup-dotnet@v3.0.2
        with:
          dotnet-version: 6.0.x

      - name: Restore
        run: dotnet restore DemoApp/DemoApp.sln

      - name: Build
        run: dotnet build --configuration Release --no-restore DemoApp/DemoApp.sln

      - name: Test
        run: dotnet test --no-restore DemoApp/DemoApp.sln
